### ISSUE TITLE
add old backstab skill

### ISSUE THREAD

**Issue by DankBudd** [LegendsOfDota/LegendsOfDota#236]
Would it be possible to put the old backstab back into the mode? 
So you could have backstab without perma invis.

The main reason I, and I'm sure others, want this is because backstab can be a strong skill with high agility. However, most of the time Cloak and Dagger is banned either due to Op bans, or Invis bans. (And even when those are disabled it still gets banned because perma invis is always annoying)

**Comment by ash47** [comment]
I'll consider it if someone else implements it as a custom abiltiy, I won't be implementing this.

**Comment by ash47** [comment]
Changed the tags as per the new system of adidng new abilities.

**Comment by DankBudd** [comment]
I made this skill, seems to be working properly, but I don't know what to do with it on github
I also don't know if it's "up to par" with the way you code things on LoD. If you directed me to some kind of guidelines or something I could edit it as needed.

**Comment by ash47** [comment]
https://github.com/LegendsOfDota/LegendsOfDota#coding-style-guide

**Comment by Jexah** [comment]
Props to you for considering these questions. +1 rep.

**Comment by DankBudd** [comment]
i got lod working offline with the help of darklordabc, i believe i put my files in the right places, but i cant figure out how to add backstab to the customs skills tab.
ive looked through most if not all of lods files with no prevail. maybe i missed something simple?

**Comment by Njol** [comment]
@DankBudd You might want to look at this: https://github.com/Pizzalol/SpellLibrary/blob/master/game/scripts/vscripts/heroes/hero_riki/cloak_and_dagger.lua
Maybe you already used that, but if you didn't you can use it to check that your code does similar things (like the particels and sound)

And about the implementation issues: A quick search in this repo lead to src/scripts/vscripts/skillmanager.lua, which deals with abilities and at the beginning loads a bunch of files - I suggest you take a look at those.

**Comment by DankBudd** [comment]
Thanks Njol, that wasn't the exact file i needed, but it helped me find what i was looking for.

**Comment by DankBudd** [comment]
welp, this makes me feel really dumb. i cant get the 'agility damage mult' and 'backstab angle' tooltips to display on the skill. http://imgur.com/a/zIEOe
(i just gathered up the tooltips for the image, they follow the..pattern? that the other tooltips follow)

i tried to do what Noya's guide said, but i guess im missing something simple again T.T

**Comment by Njol** [comment]
Which git tool are you using?

Basically, you want to 1) commit your changes, 2) push them to your fork of this repo, and 3) make a pull request.

1 and 2 are done with your git tool (if it's got a GUI then just look for "commit" and "push", otherwise find tutorials on the internet), and 3 can be done directly on github when you have your fork open.
