### ISSUE TITLE
OLD Abilities and Multicast change

### ISSUE THREAD

**Issue by edotenseilove** [LegendsOfDota/LegendsOfDota#311]
I recommend to add benefits to ogre magi abilities from multicast like
Fire Blast
 Multicast Level 1 : 95/105/115/125 mana, 10 seconds cooldown
Multicast Level 2: 115/125/135/145 mana, 8 seconds cooldown
Multicast Level 3: 135/145/155/165 mana, 6 seconds cooldown

Ignite 
Each level of Multicast increases the cast range by 150 and the area of effect of Ignite by 150.
 This results in a total cast range of 700/850/1000/1150 cast range and radius of 0/150/300/450

Bloodlust
Each level of Multicast reduces the cooldown by 5 seconds, resulting in a 15/10/5 seconds cooldown.

Also please add old riki abilities doom abilities bloodseekr and so on and I will be happy to see option  to choose mode that allows to choose from  replaced abilities like for example 
Treant Protector abilities:
http://dota2.gamepedia.com/Treant_Protector#Replaced_abilities
Centaur Warrunner
http://dota2.gamepedia.com/Centaur_Warrunner#Replaced_abilities
Bristleback
http://dota2.gamepedia.com/Bristleback#Replaced_Abilities
storm spirit
http://dota2.gamepedia.com/Storm_Spirit/Old

and so on

**Comment by ash47** [comment]
This basically entails writing a whole bunch of new skills, this isn't a
trivial thing to do, I'll certainly consider merging it if someone else
does an excellent job of coding this

**Comment by ash47** [comment]
Best I can really do is allow the standard multicast back in, as a seperate ability.

**Comment by ash47** [comment]
i added normal multicast in the repo

**Comment by ash47** [comment]
This is basically all I will do from this, you can pick from the normal multicast that does what you say, or you can have the multicast that procs on most spells.
