### ISSUE TITLE
Bots > 6v6

### ISSUE THREAD

**Issue by XAgent1990** [LegendsOfDota/LegendsOfDota#338]
Atm bot games don't work with over 6v6 as the interface in the game is being prepared screen is too big and the ready button is therefore unclickable

**Comment by ash47** [comment]
Doh :( Will look into this when I get a chance, what aspect ratio are you using?

**Comment by Myrl** [comment]
I'm using 5:4. I'll test this too.

**Comment by XAgent1990** [comment]
i am using 16:9 1920:1080 the problem seems to be that bots fields are made smaller to fit, but for some reason the player slots are normal size, being to big for a to big team

**Comment by ash47** [comment]
Fixed it:

![fixed](http://i.imgur.com/kAc9eSb.jpg)
