### ISSUE TITLE
new essence shifts work with illusions

### ISSUE THREAD

**Issue by DankBudd** [LegendsOfDota/LegendsOfDota#340]
illusions of a hero with int or str essence can steal stats.

**Comment by Myrl** [comment]
I'll look into this.

**Comment by darklordabc** [comment]
Can confirm.

**Comment by DankBudd** [comment]
you can also steal stats from illusions with the new essence shifts

**Comment by ash47** [comment]
Good job on testing, sigh

**Comment by Jexah** [comment]
If these issues do not get fixed within the next day, the abilities should be added to OP abilities list, and another patch must be uploaded. Secondly, the patch to the abilities that fixes these bugs will be delayed until the next big patch.

Additionally, whoever made the skill and submitted the pull request should be put under scrutiny for further submissions.

**Comment by darklordabc** [comment]
The essence shift was the one in the spell library, so that must be bugged too. I'm sure this is an easy fix that @Myrl can handle. As for the "intellect" part, there is a pull request already to fix that.

**Comment by Jexah** [comment]
Ah, didn't notice the pull request. Thanks.

**Comment by darklordabc** [comment]
@Myrl has fixed the issues. 

Btw, I tested essence shift strength with @DankBudd , and it is OP especially on right-click heros. At late game, when its right-clickers vs right-clickers, the other builds can't deal with the sheer amount of tankiness that essence-shift strength gives, you can have like 7k health and they have 3k. Recommend adding just the strength one to OP, intelligence one is rather pathetic compared to strength and agility.

**Comment by TheRisen41** [comment]
Is it intentional that you can have all 3 versions of essence shift at the same time?

**Comment by Myrl** [comment]
@TheRisen41 I guess so. I had a different version where it is based on your primary stats.

**Comment by TheRisen41** [comment]
@Myrl kk thx

**Comment by Myrl** [comment]
@Jexah More than half of the code was taken from the SpellLibrary. Any bug that manifested there also gets manifested on my code. I had fixed the bugs that are obvious such as the tooltips, but the illusion was less obvious.

**Comment by Jexah** [comment]
@Myrl That's okay, I don't care about spell libraries and excuses, the fact is that the code that got submitted (and tested) had a couple of critical bugs.

**Comment by Myrl** [comment]
@Jexah I guess we can put it at that.

**Comment by ash47** [comment]
This was fixed in a pull request. Build is yet to roll out onto the workshop.
