### ISSUE TITLE
Move modified abilities to Custom tab.

### ISSUE THREAD

**Issue by Jexah** [LegendsOfDota/LegendsOfDota#341]
*Please mark this as under review.*

Now that we have a custom tab, an argument is to be made that abilities that do not provide default behaviour should be housed here, such as modified Multicast, modified Aftershock, and modified Rearm.

I see the value in reserving the custom tab for entirely new skills, such as Essence Shift (Strength) and Essence Shift (Intelligence), but in my humble opinion, it would solve the issue of people thinking they're getting the original versions, when they are very clearly banned, and the new version is added to a separate tab.

Thoughts?

**Comment by darklordabc** [comment]
Good idea

**Comment by Jexah** [comment]
Oh, I didn't notice you made this recommendation 2 days ago in another thread, haha. Needed it's own issue anyway.

**Comment by TheRisen41** [comment]
Cool so can we submit custom abilities to this tab now?

**Comment by ash47** [comment]
You can but every ability will be discussed, we won't just blindly add new
abilities. Additionally, abilities need to be maintained, if I didn't make
an ability, i won't maintain it, I'll simple remove it from the custom tab
it it's causing issues until someone fixes its bugs

**Comment by TheRisen41** [comment]
@ash47 yeah sure thing

**Comment by ash47** [comment]
Cool, lets make it happen :)

**Comment by ash47** [comment]
This is pretty much done
