### ISSUE TITLE
Spell Steal is severely bugged.

### ISSUE THREAD

**Issue by darklordabc** [LegendsOfDota/LegendsOfDota#344]
![image](https://cloud.githubusercontent.com/assets/16277198/15980799/83505dba-2fb1-11e6-8b1c-9c6ead89f782.png)

Hes right, I tested it. If you get spell steal, it forces your hero to have 4 abilities, and even if you set the max abilities to 4, and then try to steal a spell, it crashes the game. 

**Recommendation:** Remove Spell Steal from the game until it can be fixed.

**Comment by ash47** [comment]
It's not a bug when it's intensional:

https://github.com/LegendsOfDota/LegendsOfDota/blob/master/src/scripts/vscripts/skillmanager.lua#L466-L480

It's also not possible to random spell steal:

https://github.com/LegendsOfDota/LegendsOfDota/blob/master/src/scripts/kv/bans.kv#L495

There was a warning about spell steal that was  part of the old LoD, I guess it wasn't ported to the new version of LoD.

**Comment by darklordabc** [comment]
I'm in a game now, but I don't think it works even when you have 4 abilities. I've only tried it once, but it crashed. I'll test it again soon.

**Comment by darklordabc** [comment]
Tested it with bots, twice, with max 4 slots, and spell steal crashes the game. The only thing that the console says is 
```
[ W General              ]: Attempted to find unknown particle system ""
[ W General              ]: Attempted to find unknown particle system ""
[                        ]: Disconnected From 'Localhost:29000'
```

**Comment by darklordabc** [comment]
If you do it with 5 slots, the stolen spell replaces spell steal, permanently i think. If this is intended, to replace spell steal temporarily, than it should not matter the number of ability slots. 
![image](https://cloud.githubusercontent.com/assets/16277198/15982015/6a1bb42e-2fc1-11e6-9833-e3a948f68407.png)

**Comment by ash47** [comment]
I kind of want to make my own spell steal from scratch, and fuck the doto
one off. The way it would work is that you select spell steal, and then
there are 5 abilties that go with it, each representing a slot, you can
have as many or few of these slots as you want (0 - 5), if you have 0, the
skill will be useless. Basically, it will let you replace the "slots" with
spells, one after another, and then loop back around once all your slots
are filled, probably just make the abilities stay in the slots forever,
cause meh.

**Comment by darklordabc** [comment]
How would you choose how many slots you wanted to use, or would it use all the remaining ones by default. E.g. its 6 slots max, I pick spell steal as my 6 slot ultimate, and the other slots are empty when the game starts waiting to be filled with empty spells?  Because I like that idea, but I think you would have to make spell steal enabled from level 1 in that case.

**Comment by ash47** [comment]
You use those spells I mentioned, to fill the slots that you want to be
swapped, 0-5

**Comment by darklordabc** [comment]
I get you now. So those 5 abilities are like containers for stolen spells, take as many containers as you want. Ya thats a cool idea, only concern is if people choose spell steal without the containers.

**Comment by darklordabc** [comment]
Lol I was going to be more forgiving and suggest that if you pick spell steal without the containers, you get a random ability instead.

**Comment by Jexah** [comment]
Yeah, and with the custom skills tab we have now, there are no excuses. We can describe the behaviour in the tooltip.

**Comment by darklordabc** [comment]
Come to think of it, there are around 9 abilities that are useless without accompanying abilities, might be an idea to add a precheck that replaces swaps them with random abilities.e.g. picking teleport to orb without pucks orb. Hardly a high priority tho just a thought.

**Comment by ash47** [comment]
I think that's a dumb solution.

**Comment by darklordabc** [comment]
Dumber than letting players pick abilities that are useless?

**Comment by ash47** [comment]
yes, that's why I said it.

**Comment by darklordabc** [comment]
Meh, well i disagree but what ever

**Comment by Jexah** [comment]
If somebody gets a random ability they think the game is bugged and they don't actually know why they didn't get what they picked.

If somebody gets a skill that requires another skill to work, they can at least put two and two together and next time they know what's up.

**Comment by ash47** [comment]
If you change someone's abilities without telling them why, they will pick
that ability again to try to work out wtf happened. If you let them mess up
their build, they will work out it's useless and learn after only one round.

**Comment by darklordabc** [comment]
Fair point.

**Comment by ash47** [comment]
it's removed for now.
