### ISSUE TITLE
Custom Abilities Tab is Not visible on 4:3 Ratio

### ISSUE THREAD

**Issue by darklordabc** [LegendsOfDota/LegendsOfDota#351]
The custom abilities tab is obstructed or not visible at all on 4:3 ratio video settings. 

A quick solution would be to combine the custom abilities tab and wrath night tabs. Wrath night abilities are basically custom abilities from the perspective of casual Dota players anyway, and there is only like 5 of them, they don't really warrant their own tab. 

![image](https://cloud.githubusercontent.com/assets/16277198/16079735/6b7aacbe-3348-11e6-902f-848d6479a943.png)

Credit:
![image](https://cloud.githubusercontent.com/assets/16277198/16079776/92d471f0-3348-11e6-8a59-8efe31e8fc54.png)

**Comment by Jexah** [comment]
The sensible thing to do would be to make the tabs much shorter. Maybe like 100px wide.

Or if Dota supports it, just set percentage width to `1 / [number of tabs]`.
