### ISSUE TITLE
Rare bug: Can't Draft Abilities (Mirror Draft)

### ISSUE THREAD

**Issue by darklordabc** [LegendsOfDota/LegendsOfDota#354]
Played Mirror Draft, a thing a player disconnected very early, maybe on load, when the game started, and my draft heros came up, most of them I could not choose abilities from, with the error saying that the ability was not from my list of draftable abilities. 
[Video](https://drive.google.com/file/d/0B7dpugx95_vaRDBMam1URkFHdmM/view)

**Comment by ash47** [comment]
I think I know why this is, and I can PROBABLY write a patch to fix this.

**Comment by darklordabc** [comment]
Helps not appreciated, so I'll just withdraw.

**Comment by ash47** [comment]
That commit should fix the issue, will perform more aggressive testing later.

**Comment by ash47** [comment]
I am considering this closed.
