### ISSUE TITLE
Overlay cosmetic bug

### ISSUE THREAD

**Issue by darklordabc** [LegendsOfDota/LegendsOfDota#355]
When the countdown begins warning players to pick a hero, it prevents the heroes underneath the overlay (in center of screen) from showing their stats. Perhaps you can make the timer "not-clickable". 
[Video](https://drive.google.com/file/d/0B7dpugx95_vaVThLeWdWcndmT00/view) 
Credit:
![image](https://cloud.githubusercontent.com/assets/16277198/16203152/2d9758bc-375c-11e6-945e-8d8fd4d80eff.png)

**Comment by ash47** [comment]
This has been fixed.
