### ISSUE TITLE
Can't play LOD after DotA last update

### ISSUE THREAD

**Issue by AceHank** [LegendsOfDota/LegendsOfDota#362]
After the last update today, June 23rd update, I can't play LOD. And so is my friend. Everytime I connect to a game, DotA will quicly force close. I tried to play it offline using the console, and same thing happenned. I wonder why this happens. And I believe this issue has connection to the latest Dota update.

Thanks in advance.

**Comment by Myrl** [comment]
I think the new update broke a lot of DotA mods.

**Comment by bhimo** [comment]
Yeah I got the exact problem, could it be fixed soon? bc i liked this custom game more than the original dota itself

**Comment by AceHank** [comment]
Well, so what we can do is to wait for it to be fixed? I'll wait then.

**Comment by ash47** [comment]
This has been fixed.
