### ISSUE TITLE
Scepter upgraded Arctic Burn triggers Essence Aura

### ISSUE THREAD

**Issue by Njol** [LegendsOfDota/LegendsOfDota#364]
Arctic Burn has no cooldown with scepter, so this combo can be used for infinite mana.

**Comment by DankBudd** [comment]
it also allows you to perma stun with aftershock.
pugna's ultimate does both of these things as well

**Comment by Jexah** [comment]
Nice catch Peter.

Is the standard Aftershock banned unless OP abilities are enabled?

On 27/06/2016 4:52 am, "DankBudd" <notifications@github.com> wrote:
>
> it also allows you to perma stun with aftershock.
> pugna's ultimate does both of these things as well
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
<https://github.com/LegendsOfDota/LegendsOfDota/issues/364#issuecomment-228616188>,
or mute the
<https://github.com/notifications/unsubscribe/AFINyO6qbCLCfxUTWNiOjZf5Z4FJDUzFks5qPsqCgaJpZM4I-jmA>thread.

**Comment by ash47** [comment]
Essence aura is a custom ability, we can just white list it to fix this

**Comment by ash47** [comment]
I guess this is fixed?
