### ISSUE TITLE
Change default quantity of skills to ban from 10 to 2...5. And reduce banning phase to 30 sec

### ISSUE THREAD

**Issue by LODonly** [LegendsOfDota/LegendsOfDota#370]
Please change default quantity of skills to ban from 10 to 2...5. And reduce banning phase to 30 sec. These changes will make banning more popular. Currently it takes a lot of time and 100 skills to ban is too much

**Comment by ash47** [comment]
https://github.com/LegendsOfDota/LegendsOfDota/issues/251
