### ISSUE TITLE
Hero Builder suggestions. 

### ISSUE THREAD

**Issue by ryanwilson112** [LegendsOfDota/LegendsOfDota#373]
Hero Builder changes / bugs: 

Some skills are missing their dota 2 search terms. Usually they have both their Dota 1 name and Dota 2 name for ease of both new and old players. But I think it's most important to fix the missing Dota 2 search terms for now. Heroes have their search terms just fine. 

**Missing Dota 2 search terms:**
- Lich has Dota 1 "Dark Ritual" but missing Dota 2 "Sacrifice".
- Alchemist has Dota 1 "Goblins Greed" but missing Dota 2 "Greevils Greed". 

**"Stuns" category:**

Hero normal stuns currently not included: 
- Leshrac's Split Earth.
- Lion's Earth Spike.  
- Sand King's Burrowstrike.
- Jakiro's Ice Path. 
- Witch Doctor's Paralyzing Cask.

Neutral stuns currently not included:
- Golem's Hurl Boulder. 

Hero Ultimate stuns currently not included:
- Tidehunter's Ravage should be added, if others ult stuns are already added. 
- Medusa's Stone Gaze should be added, above. 
- Pudge's Dismember should be added, above.
- Beastmaster's Primal Roar should be added, above.
- Winter Wyvern's Winter's Curse should be added, above. 
- Bane's Fiend's Grip should be added, above. (Also, Shadow Shackle's note below will apply here too)

Less obvious stuns that should be added: 
- Shadow Shaman's Shackles. (What seperates this and abilities like Hex is that Shackles will stop movement and turning which those disable abilities don't. Shackles is considered the longest lasting stun minus Aghs upgraded Fiend's Grip)
- Invoker's Cold Snap should be considered a stun (0.4 seconds) and added to the category, similar to that of Flamebreak's low duration stun. 
- Tusk's Walrus Punch should be considered a stun (1 second), just worded differently. Similar to that of Echo Stomp or Cold Snap (If it's added) in regards to it's different wording. (Sleep / Frozen)

- Crystal Maiden's Frostbite has a 0.1 ministun at the very beginning of the spell and should be added. Similar to that of Shuriken Toss, Battery Assault and Thunder Strike.
- Night Stalker's Void also has a 0.1 ministun and should be added. Similar to all mentioned above.
- Sniper's Assassinate also has a 0.1 ministun and should be added. Similar to all mentioned above. 

- Wisp's Tether is in the category but it doesn't stun nor even mini-stun to interrupt TPs, channeling or anything a stun would normally be expected to do. I don't think it belongs there and should be removed. 

Honorable mentions: 
Abilities like Blackhole, Flaming Lasso and Electric Vortex are technically called shackles because the user needs to channel it or are disabled in some form to use it. Disarms / Slows for latter two. Similar to Fiend's Grip, Shaman Shackle's and Disember which are also channeled. The reason those 3 aforementioned don't become stuns though is because they don't disable movement and/or turning of the enemy. They're all about moving the enemy with their disable. So no matter what happens, they'll never find themselves in either mini-stun or stun category. It would be added to an alternative disable category if you were to ever do that. 

If you guys agree to it, I can do a similar check of all other categories. And could break them down in the ministuns, autocast or disable categories for starters. For now, it seems like fixing Stuns alone is quite an ask. 

I'm also liable to make mistakes, I nearly missed Witch Doctor Cask. So it might not be perfect but I believe it'd be better than what it is.

**Comment by ash47** [comment]
Pretty sure you can just search for lich too

**Comment by ryanwilson112** [comment]
You can, I usually do, it's just a minor annoyance that might waste a few seconds during drafting phase.

**Comment by ryanwilson112** [comment]
Could this be renamed to "Hero Builder suggestions" or something along those lines? I've edited my original post to add **a lot** more things that are related to categories, etc. That I believe could improve the hero building stage. 

This is very much a **"quality of life"** suggestion. It is NOT essential nor vital. But it could help speed up ability choice for new players who might not be sure of what to pick. The category filtering is amazing for those players but currently doesn't give them everything there is to consider which I believe isn't intentional. I also think there's huge opportunity to add new filters such as autocast or mini-stuns instead of grouping stuff together as it is in Stuns and Attack Modifiers. Although those umbrella terms are technically correct. After adding so many abilities splitting it down further should help simplify it.

Open to discussion, let me know what you think of this please.

**Comment by Snoresville** [comment]
what about magnus? searching magnus by itself wont get anything, but magnotaur or however it's spelled gets magnus' skills

**Comment by ryanwilson112** [comment]
Magnataur, yeah. There must be a few of these outdated Dota 1 names, I could also check every skill and hero and make sure those are fixed for convenience. I doubt anyone is using them. 

But it depends on who and whether or not someone actually wants to do this quality of life suggestion. And how much they actually want to do. There's a massive amount of room for improvement but absolutely none of it is essential nor in demand minus myself. ( :D )

**Comment by ash47** [comment]
I have fixed the searching issue, you can now find sacafice, lol, as far as stuff being flagged correctly, feel free to update this:

https://github.com/LegendsOfDota/LegendsOfDota/blob/master/src/scripts/kv/flags.kv

Make it as complex as you like, you can add more categories if you so choose, if it is done well, I will vastly improve the ingame skill finder's category search system :)

**Comment by ryanwilson112** [comment]
Awesome, thanks! A new benefit of fixing the localize is that searching with proper grammar, including your apostrophe in Greevil's Greed, now actually works. Wooo. 

Darklord made an awesome change to the search system I helped with a little. Hopefully he makes a PR soon, I think it's the vast improvement you want! :)

A few new categories, a lot of the stuff I mentioned here and even more were given the flags they deserve and the UI was changed too. Which you can see here: http://prntscr.com/bqdazt

**Comment by ash47** [comment]
Cool, although, that three tab thing to switch between the three things
won't work in the new version of Legends of Dota as there are more than 3,
and a lot more to come, as per the original plan.

**Comment by ryanwilson112** [comment]
Oh right. No problem then. 

I'll submit the PR for the new categories and flags in an hour or so.

**Comment by ash47** [comment]
cool :)

**Comment by ash47** [comment]
I think this was done. Thanks,
