### ISSUE TITLE
Troll Combo: Witchcraft + Hurl Boulder = infinite and free stun

### ISSUE THREAD

**Issue by Njol** [LegendsOfDota/LegendsOfDota#376]
edit: Brew's boulder, not the neutral one

**Comment by Jexah** [comment]
Isn't Hurl Boulder already an OP skill?

**Comment by Njol** [comment]
that has nothing to do with it being a troll combo

**Comment by Snoresville** [comment]
witchcraft does not reduce cooldowns below 1 second, unless it's a rare interaction

**Comment by Njol** [comment]
@Snoresville which completely doesn't matter since reducing a 5 second cooldown by 4 seconds is one second anyway, and that on a free (0 mana) 2 second ranged stun.

**Comment by Snoresville** [comment]
well maybe you just have to kill that troll straight away before it does something or get magic immunity or a sort of invis

**Comment by ash47** [comment]
This is a case of "i dont really care", I will merge it, but, if people are playing with OP skills enabled, there is a good chance they will have troll combos off, so, this won't even really do anything.
