### ISSUE TITLE
Chakram 2 is not an ult

### ISSUE THREAD

**Issue by Njol** [LegendsOfDota/LegendsOfDota#382]
IDK if that should be changed or not, but just FYI.

**Comment by LODonly** [comment]
It'll be too op if make it available at 1st lvl. Anyway it's still very poverful if you take Chakram 1 + Chakram 2 and Essence Aura

**Comment by Njol** [comment]
The issue is mostly that you can take 3 ults even with the limit of 2 in all pick, since Chakram 2 is not classified as ult.

**Comment by ash47** [comment]
Marked it as an ultimate.
