### ISSUE TITLE
make black hole green

### ISSUE THREAD

**Issue by Snoresville** [LegendsOfDota/LegendsOfDota#387]
because it has a 420 radius

**Comment by applevac** [comment]
...is this really in the issues forum? Seriously snoresville, is this a game-breaking bug? xD

**Comment by DankBudd** [comment]
i second this argument for green black hole

▄░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░▄
░_____________________█______________________░
░____________________██______________________░
░___________________████____________________░
░_____█____________█████__________█________░
░_____██__________██████_________██_______░
░_____████_______███████_______███_______░
░_____██████____████████____█████______ ░
░__█_____██████__██████__███████___█___░
░_██______██████_█████_████████____██_ ░
░_████_____██████_███_██████_____█████ ░
░__█████████__████_█_███_█_█████████_ ░
░_____█████████__█_█_█_███████████____ ░
░_________█████████████████████________░
░_______________███_█_████_________________░
░_____________█████_█__█████______________░
░___________██_______█_______██_____________░
░____________▀______▄█▄_______▀_____________░
░░░░░░░░░░░░░░░░.░░░░░░░░░░░░░░░░░░░
░░░░░░░░░.▄██░░░░░░░░░░░░░░░░░░░░░░░
░░░░░░░░.▄███░░▄███▄░░░▄▄▄▄░░░░░░░░░
░░░░░░░.██▀██░░██▀██░░██▀▀██░░░░░░░░ 
░░░░░.▄██▄▄██▄░░▄██▀░░██░░██░░░░░░░░ 
░░░░░░░░░░.██░░███▄▄░░██▄▄██░░░░░░░░ 
░░░░░░░░░.▄██▄░░░░░░░░░▀▀▀▀░░░░░░░░░
░░░░░░░░░░░░░░░░.░░░░░░░░░░░░░░░░░░░
▀░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░▀

**Comment by Jexah** [comment]
+1

**Comment by Myrl** [comment]
@applevac Issues don't necessarily mean bugs or problems. :P

**Comment by ash47** [comment]
I dont understand?

**Comment by Myrl** [comment]
@ash47 Marijuana joke.

**Comment by Myrl** [comment]
#rekt. #savage.
