### ISSUE TITLE
Heroes getting stuck in map

### ISSUE THREAD

**Issue by Jexah** [LegendsOfDota/LegendsOfDota#391]
Fix that bug I showed you Ash, you giant scrublord.

**Comment by ash47** [comment]
This is actually top of my todo list, have been working on this a lot today, I am getting closer to narrowing down this issue, will need you to test with me again later when you have some spare time :/

**Comment by ash47** [comment]
@Jexah This has been pushed onto the workshop already, as per our testing, it seems to be working fine.

Thanks :D

**Comment by ash47** [comment]
This is working fine. All good.
