### ISSUE TITLE
Geostrike + Juxtapose = troll combo?

### ISSUE THREAD

**Issue by LODonly** [LegendsOfDota/LegendsOfDota#395]
I'm sure everybody knows this skills combo. 
Do you think it's troll combo or it's balanced strong skill combo?

**Comment by ash47** [comment]
Given me and others use this all the time, and it may possibly be a
recommended build.....

**Comment by Jexah** [comment]
I don't think it's OP, but it should be a recommended build. It has no
escape, gets countered by cleave, splash, split push, and escapes, and
can't farm very fast. If you try to fight into it 1v1 without a hard
counter, you're in trouble, but there are a lot of builds like that that
aren't OP for the same reason. It's a very "one trick pony" build.

**Comment by Snoresville** [comment]
you can blink out of it, and also it's in one of the combos in the default build
