### ISSUE TITLE
illusions will use starfall scepter upgrade

### ISSUE THREAD

**Issue by DankBudd** [LegendsOfDota/LegendsOfDota#397]
http://imgur.com/a/ngXrf
kek

**Comment by Jexah** [comment]
Toppest of keks, looks like fun.

**Comment by applevac** [comment]
Just played with one of these guys.... no fair at all. Just used haunt and killed about 3 of us every time.

**Comment by ash47** [comment]
XD it's a pretty easy fix, will fix
