### ISSUE TITLE
Neutral Abilities of Ancient Creeps

### ISSUE THREAD

**Issue by XAgent1990** [LegendsOfDota/LegendsOfDota#401]
So, what I realised was that from the three ancient creep auras that there are in DotA, only the Granite Aura from the Ancient Granite Golem is still in LoD, and I still remember all of them being in the gamemode. So I can think of why the Dragonhide Aura isn't activated anymore, as it probably caused some "OPness" when combined with an illusion build, as this aura stacks and all illusions would be having this aura. But still this may could be fixed so it only works on original heroes (somehow maybe) and it also does not explain why the War Drums Aura from the Ancient Thunderhide isn't available anymore, which is my main complaint, as I really like it and picked it many times and I really don't understand what problem it is causing.

**Comment by DankBudd** [comment]
i believe they were both removed for the same reason, the aura's stacked.
you're right, we could remake it so that it would only work on real heros, but for that to work... someone actually has to remake it.

**Comment by ash47** [comment]
They were removed because they grant magic immunity
