### ISSUE TITLE
Pre build recommend

### ISSUE THREAD

**Issue by rawinza555** [LegendsOfDota/LegendsOfDota#402]
Name: Super Rat
Hero: Mirana
Skills: Blur, fervor,geminate attack, NP's teleport ,marksmanship, phantasm

Blur to make hero disappear from the map then just push to the rax. So useful when enemy doesn't have enough map awareness.

**Comment by DankBudd** [comment]
do illusions even proc geminate atk?
they definitely dont use fervor, i really dont see why phantasm is a part of this build

**Comment by rawinza555** [comment]
Well, I can't use Grow since it's in LOD ban list now so I replace it with Phantasm. These illusion deal 100% damage and have marksmanship so it gives me like 4x dmg boost over a certain amount of time. Not the ideal replacement for grow though. I tried to use sth else that affect the illu like curse of Avernus or BM atk speed aura but I feel like using fervor + geminate is better just in case Phantasm is on CD so u can go solo. Also, Phantasm can be used to dodge stuffs and create some chaos too!

I'm Doge Seer btw.

**Comment by Snoresville** [comment]
better off using demolish over geminate attack, and also there's a better version already added in the game sooo
