### ISSUE TITLE
Quick question about old skills

### ISSUE THREAD

**Issue by applevac** [LegendsOfDota/LegendsOfDota#403]
Hey, just gonna write this before I go to bed. I noticed you added back "backstab" for riki. Is it possible to add a couple of other skills like level death and doppelwalk back into the game? Thanks in advance.

**Comment by ash47** [comment]
If someone else implements it.

**Comment by applevac** [comment]
What do you mean if someone else implements it? Sorry, I'm still a little new to the whole LoD process.

**Comment by ash47** [comment]
My efforts are better spent else where, implementing new abilities is
mostly a waste of my time.

Anyone can contribute to legends of Dota, it's on GitHub after all

**Comment by applevac** [comment]
Okay. Maybe at some point I'll browse through the files and get some material for ya.

**Comment by ash47** [comment]
This seems resolved.
