### ISSUE TITLE
Vote System Suggestions

### ISSUE THREAD

**Issue by XAgent1990** [LegendsOfDota/LegendsOfDota#406]
I love the new voting system really much! I think another cool thing to be added would may be a vote to toggle the All Vision option, other than that very cool system, didnt have any problems with it yet, works flawless so far, keep up the good work! ☺☻

**Comment by ash47** [comment]
Yes, I was thinking this too, along with global Shop and wtf mode, I had a
few other ideas but they are very complex.

**Comment by XAgent1990** [comment]
thought about that too, I just didn't suggest it as i thought global shop would be difficult to implement and wtf mode would make problems, as it would ban certain abilities in the beginning :/
