### ISSUE TITLE
All Random no longer provides five builds to pick from.

### ISSUE THREAD

**Issue by AlphaRage** [LegendsOfDota/LegendsOfDota#409]
It provides you with one build though but you cannot see that in the main window. It seems like that window in the center is broken and there are five builds created but you just cannot pick them.

![20160801013545_1](https://cloud.githubusercontent.com/assets/16274094/17280119/54efc542-5788-11e6-9948-398ee9fc16c0.jpg)

**Comment by ash47** [comment]
I might know why, will take a look soon :)

**Comment by ash47** [comment]
Let me know if it was fixed?

**Comment by AlphaRage** [comment]
Sorry, the answer went to my spam folder for some reason.

Yes, it was fixed, thanks! However I'm opening another issue for a problem related to All Random again.
