### ISSUE TITLE
Voting bug

### ISSUE THREAD

**Issue by Njol** [LegendsOfDota/LegendsOfDota#410]
Starting a vote during the results screen f a previous vote causes the new vote screen to disappear when the old one would, winning automatically if nobody can vote 'no' in the short time it is still there.

fix: Restart the timer when a vote starts, even if there already is a timer running (or stop the old timer before starting a new one), or prevent starting a vote during the 5 seconds after a vote ends and the results are displayed.

**Comment by Njol** [comment]
apparently fixed in the recent update

**Comment by ash47** [comment]
Thanks dude, the main thing is telling me an issue exists, as soon as I
know an issue exists, and I can reproduce it, it's easy to fix :)
