### ISSUE TITLE
Voting Bug "It Ruins Experences"

### ISSUE THREAD

**Issue by yolosuckysucky** [LegendsOfDota/LegendsOfDota#413]
If one people create vote while another vote is pass. vote is unable to show interface and automatic passes  .
Idea of Fix : 1:how about a multiple vote window interface?
2: how about vote can only pass every 1 min into the game w anybody. not as individual. Ex : windrunner has created a vote. it didn't passes. Earth shaker now wants to vote. but he have to wait 1 min before creating another vote.

Thx for reading. sry for bad english and grammer

**Comment by ash47** [comment]
Ez for be to fix, will fix soon
