### ISSUE TITLE
New voting bug

### ISSUE THREAD

**Issue by Njol** [LegendsOfDota/LegendsOfDota#415]
Voting ends when 5 people (half the number of players?) voted, and all votes pass (though I've never seem more than 2 "no" votes, so 3 might cause a vote to fail)

**Comment by ash47** [comment]
think this is fixed, please confirm this, just pushed an update.

**Comment by Njol** [comment]
Right, there was an update 20 minutes ago. I will close this issue if the the bug is fixed.

**Comment by Njol** [comment]
works - votes fail at 4 no votes, and pass with enugh yes votes.
