### ISSUE TITLE
Clicking on an ability/hero and then on a build slot doesn't work anymore

### ISSUE THREAD

**Issue by Njol** [LegendsOfDota/LegendsOfDota#416]
It doesn't work both in the ban and the pick phase - the "ban ability" button even results in the error message <'' is not a valid ability>.

Dragging heroes and abilities to the build slots/ban field works though.

**Comment by ash47** [comment]
Lol, opps, ok, will fix this soon.

**Comment by quietdrive** [comment]
im also experiencing this issue. While other players can ban I cannot because of this error '' is not a valid ability.

**Comment by ash47** [comment]
Drag and drop still works right?

**Comment by Njol** [comment]
That's the only way to make builds right now.

**Comment by ash47** [comment]
This has been fixed, it will roll out in the next update.
