### ISSUE TITLE
Heroes / skills being displayed wrongly in UI (custom)

### ISSUE THREAD

**Issue by puppybull** [LegendsOfDota/LegendsOfDota#420]
Recently, maybe one week or so ago, whenever I host custom mirror draft

{"lodOptionBanning":3,
"lodOptionBanningHostBanning":1,
"lodOptionBanningMaxBans":1,
"lodOptionBanningMaxHeroBans":0,
"lodOptionBanningUseBanList":1,
"lodOptionSlots":6,
"lodOptionCommonMaxSlots":6,
"lodOptionUlts":2,
"lodOptionCommonMaxUlts":2,
"lodOptionGamemode":-1,
"lodOptionCommonGamemode":3,
"lodOptionCommonMaxSkills":6,
"lodOptionBanningBlockTrollCombos":1,
"lodOptionBanningBanInvis":0,
"lodOptionGameSpeedStartingLevel":6,
"lodOptionGameSpeedMaxLevel":25,
"lodOptionGameSpeedStartingGold":500,
"lodOptionGameSpeedGoldTickRate":2,
"lodOptionGameSpeedGoldModifier":100,
"lodOptionGameSpeedEXPModifier":100,
"lodOptionGameSpeedRespawnTimePercentage":50,
"lodOptionGameSpeedRespawnTimeConstant":1,
"lodOptionGameSpeedBuybackCooldown":420,
"lodOptionGameSpeedTowersPerLane":3,
"lodOptionGameSpeedUpgradedUlts":0,
"lodOptionGameSpeedFreeCourier":1,
"lodOptionBotsRadiant":5,
"lodOptionBotsDire":5,
"lodOptionBotsUnfairBalance":1,
"lodOptionAdvancedHeroAbilities":1,
"lodOptionAdvancedNeutralAbilities":0,
"lodOptionAdvancedNeutralWraithNight":1,
"lodOptionAdvancedCustomSkills":1,
"lodOptionAdvancedOPAbilities":1,
"lodOptionAdvancedHidePicks":1,
"lodOptionAdvancedUniqueSkills":1,
"lodOptionAdvancedUniqueHeroes":1,
"lodOptionAdvancedSelectPrimaryAttr":1,
"lodOptionCrazyNoCamping":1,
"lodOptionCrazyUniversalShop":0,
"lodOptionCrazyAllVision":0,
"lodOptionCrazyMulticast":0,
"lodOptionCrazyWTF":0,
"lodOptionMirrorHeroes":20,
"lodOptionCommonMirrorHeroes":20}

after the banning phase, it doesn't show the skills belonging to the heroes we drafted and instead just shows all the skills like when we were banning. A quick and easy fix is to click the Custom Abilities tab and then go back to the Hero Abilities tab on the top, which then displays skills belonging to our draft. Also, when picking a hero, it doesnt gray out the heroes we can't pick, it looks as if we can pick any hero, but we can only pick heroes from our draft. What we do is just look at our skills and figure out which heroes we drafted and then pick one of those.

**Comment by ash47** [comment]
Will take a look

**Comment by ash47** [comment]
This may be fixed with the newest update. Possibly.
