### ISSUE TITLE
Recommended Builds suggestion

### ISSUE THREAD

**Issue by XAgent1990** [LegendsOfDota/LegendsOfDota#424]
The Ultimate Rat:
I played a Single draft match and had this combination of abilities and it was waaaay better than I thought, this build takes out towers and rax in under 6 seconds and does this pretty much ever 60 seconds, every 45 with octarine.

Teleportation from Natures Prophet
Natures's Call from Natures Prophet
Test of Faith (teleportation one) from Chen
True Form from Lone Druid
Battle Cry from Lone Druid
Wrath of Nature from Natures Prophet

I suggest not going higher than level 3 on ToF as it's delay really works well with the Teleportation 3 seconds delay. Level 3 has a 4 seconds delay and is sometimes hard to manage with, so keeping it at level 2 isn't bad either.
Also you shouldn't ever use True From. It's just there as Battle Cry doesn't work without it and you also can only use Battle Cry inside of the True form if you used it once.
My suggested itembuild for this would also be Main item Aghs, Octarine Core, refresher, boots of travel and for extra damage aether lense.

The theory is this:
Step 1: Cast Nature's Call somewhere
Step 2: Cast Wrath of Nature when many creeps are visible
Step 3: Optionally cast refresher and repeat step 1 and 2
Step 4: Cast Test of Faith on yourself
Step 5: Imediatly cast Teleportation on a tower or barracks you want to put down (Backdoor doesn't matter)
Step 6: As soon as your army arrived cast Battle Cry
Step 7: Now control all your units and attack the building and watch it fade away in just a few seconds

You will probably die often but as long as you have level 16 you wont need any more experience.

**Comment by ash47** [comment]
https://github.com/LegendsOfDota/LegendsOfDota/blob/master/src/panorama/scripts/custom_game/shared/shared_builds.js

https://github.com/LegendsOfDota/LegendsOfDota/blob/master/src/scripts/kv/abilities.kv

Fill it out as per the first link, there are abilty names in the 2nd link.

**Comment by ash47** [comment]
Make a new issue with the template, otherwise, meh
