### ISSUE TITLE
Like you can import options you should also be able to import bans and builds

### ISSUE THREAD

**Issue by Disguised** [LegendsOfDota/LegendsOfDota#429]
Well title says it all I guess

The thing is it takes so long for an owner to ban abilities (with a certain degree of mistakes that can be made), being able to export/import bans would make stuff so much faster

**Comment by ash47** [comment]
I was actually thinking the same thing over the weekend, that it would be
easy to add ban importing, anyone could use it too, granted, most people
wouldn't have enough bans to ban everything they want, but still.

**Comment by ash47** [comment]
This has been implemented and rolled out in the last update.
