### ISSUE TITLE
Problem with staging and running LoD

### ISSUE THREAD

**Issue by XAgent1990** [LegendsOfDota/LegendsOfDota#430]
So there seems to be a problem, me and my m8 tried this, step by step and we noticed that the file `<lod>/dota/content/maps` refers to nothing, and maybe that is why it is not working.
So in the end when we try to run for example the custom.vpk there is just the option picking screen pretty much empty and all you can do is switch between teams until the "please wait" screen appears after 2 minutes and gets stuck there.
Also the "Legends of dota is activating!" doesn't show up in the console as it is said to do.
[![LODBUG.png](https://s9.postimg.org/dju0njt1b/LODBUG.png)](https://postimg.org/image/rdidcllmj/)

**Comment by ash47** [comment]
With staging, make sure you do not have dota open, then make a new
directory junction in dota content / have addons directory that points to
the staged directories

**Comment by XAgent1990** [comment]
Okay, copying didn't work at all, after doing it with the directory junctions it worked flawless, ty!
